sudo: false
language: python
cache:
  pip: true
  timeout: 900
branches:
  only:
  - master
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements_test.txt"
  - "pip install coverage pytest-cov python-coveralls"  # Travis-only packages
  - "rm -r **/*.pyc"
  - "pip install ."
  - "mkdir -p ./.cache"
script: py.test --cov .
after_success:
  - coveralls
