sudo: false
language: python
branches:
  only:
  - master
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coverage pytest-cov python-coveralls  # Travis-only packages
  - pip install .
  - mkdir -p ./.cache
script: py.test --cov smsc
after_success:
  - coveralls
